export interface MetroStation {
  id: string;
  name: string;
  lineId: string;
  hasTransfer: boolean;
  transferTo?: string[];
  order: number;
}

export interface MetroLine {
  id: string;
  name: string;
  color: string;
  number: string;
}

export const metroLines: MetroLine[] = [
  { id: 'sokolnicheskaya', name: 'Сокольническая', color: '#E4002B', number: '1' },
  { id: 'zamoskvoretskaya', name: 'Замоскворецкая', color: '#2DBE2C', number: '2' },
  { id: 'arbatsko-pokrovskaya', name: 'Арбатско-Покровская', color: '#0078C9', number: '3' },
  { id: 'filevskaya', name: 'Филёвская', color: '#19C1F3', number: '4' },
  { id: 'koltsevaya', name: 'Кольцевая', color: '#894E35', number: '5' },
  { id: 'kaluzhsko-rizhskaya', name: 'Калужско-Рижская', color: '#F58631', number: '6' },
  { id: 'tagansko-krasnopresnenskaya', name: 'Таганско-Краснопресненская', color: '#8E479C', number: '7' },
  { id: 'kalininskaya', name: 'Калининская', color: '#FFCD1C', number: '8' },
  { id: 'solntsevskaya', name: 'Солнцевская', color: '#FFD702', number: '8А' },
  { id: 'serpukhovsko-timiryazevskaya', name: 'Серпуховско-Тимирязевская', color: '#999999', number: '9' },
  { id: 'lyublinsko-dmitrovskaya', name: 'Люблинско-Дмитровская', color: '#B3D445', number: '10' },
  { id: 'bolshaya-koltsevaya', name: 'Большая кольцевая', color: '#82C0C0', number: '11' },
  { id: 'butovskaya', name: 'Бутовская', color: '#ACB5BD', number: '12' },
  { id: 'monorail', name: 'Монорельс', color: '#79CDCD', number: '13' },
  { id: 'mck', name: 'Московское центральное кольцо', color: '#F59BBB', number: '14' },
  { id: 'nekrasovskaya', name: 'Некрасовская', color: '#DE64A1', number: '15' },
  { id: 'troitskaya', name: 'Троицкая', color: '#DD0000', number: '16' },
  { id: 'rublevo-arkhangelskaya', name: 'Рублево-Архангельская', color: '#FFA8AF', number: '17' },
  { id: 'biryulevskaya', name: 'Бирюлевская', color: '#A1E9E9', number: '18' },
  { id: 'd1', name: 'Белорусско-Савёловский диаметр', color: '#F08521', number: 'D1' },
  { id: 'd2', name: 'Курско-Рижский диаметр', color: '#D375B9', number: 'D2' },
  { id: 'd3', name: 'Ленинградско-Казанский диаметр', color: '#11C0E7', number: 'D3' },
  { id: 'd4', name: 'Калужско-Нижегородский диаметр', color: '#B7DD7D', number: 'D4' },
];

export interface MetroTransfer {
  stationId: string;
  transferToLineId: string;
}

export const metroStationTransfers: MetroTransfer[] = [
  { stationId: 'sok-1', transferToLineId: 'mck' },
  { stationId: 'sok-2', transferToLineId: 'mck' },
  { stationId: 'sok-4', transferToLineId: 'bolshaya-koltsevaya' },
  { stationId: 'sok-8', transferToLineId: 'lyublinsko-dmitrovskaya' },
  { stationId: 'sok-8', transferToLineId: 'kaluzhsko-rizhskaya' },
  { stationId: 'sok-10', transferToLineId: 'zamoskvoretskaya' },
  { stationId: 'sok-10', transferToLineId: 'arbatsko-pokrovskaya' },
  { stationId: 'sok-11', transferToLineId: 'arbatsko-pokrovskaya' },
  { stationId: 'sok-11', transferToLineId: 'filevskaya' },
  { stationId: 'sok-11', transferToLineId: 'serpukhovsko-timiryazevskaya' },
  { stationId: 'sok-14', transferToLineId: 'koltsevaya' },
  { stationId: 'sok-15', transferToLineId: 'mck' },
  { stationId: 'sok-18', transferToLineId: 'bolshaya-koltsevaya' },
  { stationId: 'sok-26', transferToLineId: 'troitskaya' }
];

const createStation = (
  id: string,
  name: string,
  lineId: string,
  order: number,
  transfers: string[] = []
): MetroStation => ({
  id,
  name,
  lineId,
  order,
  hasTransfer: transfers.length > 0,
  transferTo: transfers.length ? transfers : undefined,
});

export const metroStations: MetroStation[] = [
  createStation('d1-1', 'Одинцово', 'd1', 1),
  createStation('d1-2', 'Баковка', 'd1', 2),
  createStation('d1-3', 'Сколково', 'd1', 3),
  createStation('d1-4', 'Немчиновка', 'd1', 4),
  createStation('d1-5', 'Сетунь', 'd1', 5),
  createStation('d1-6', 'Рабочий Посёлок', 'd1', 6),
  createStation('d1-7', 'Кунцевская', 'd1', 7, ['filevskaya', 'bolshaya-koltsevaya', 'arbatsko-pokrovskaya']),
  createStation('d1-8', 'Славянский бульвар', 'd1', 8, ['arbatsko-pokrovskaya']),
  createStation('d1-9', 'Фили', 'd1', 9, ['filevskaya']),
  createStation('d1-10', 'Тестовская', 'd1', 10, ['rublevo-arkhangelskaya', 'mck']),
  createStation('d1-11', 'Беговая', 'd1', 11, ['tagansko-krasnopresnenskaya']),
  createStation('d1-12', 'Белорусская', 'd1', 12, ['koltsevaya', 'zamoskvoretskaya', 'd4']),
  createStation('d1-13', 'Савёловская', 'd1', 13, ['serpukhovsko-timiryazevskaya', 'bolshaya-koltsevaya', 'd4']),
  createStation('d1-14', 'Тимирязевская', 'd1', 14, ['serpukhovsko-timiryazevskaya']),
  createStation('d1-15', 'Петровско-Разумовская', 'd1', 15),
  createStation('d1-16', 'Окружная', 'd1', 16, ['mck', 'lyublinsko-dmitrovskaya']),
  createStation('d1-17', 'Дегунино', 'd1', 17),
  createStation('d1-18', 'Бескудниково', 'd1', 18),
  createStation('d1-19', 'Лианозово', 'd1', 19, ['lyublinsko-dmitrovskaya']),
  createStation('d1-20', 'Марк', 'd1', 20),
  createStation('d1-21', 'Новодачная', 'd1', 21),
  createStation('d1-22', 'Долгопрудная', 'd1', 22),
  createStation('d1-23', 'Водники', 'd1', 23),
  createStation('d1-24', 'Хлебниково', 'd1', 24),
  createStation('d1-25', 'Шереметьевская', 'd1', 25),
  createStation('d1-26', 'Лобня', 'd1', 26),

  { id: 'sok-1', name: 'Бульвар Рокоссовского', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['mck'], order: 1 },
  { id: 'sok-2', name: 'Черкизовская', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['mck'], order: 2 },
  { id: 'sok-3', name: 'Преображенская площадь', lineId: 'sokolnicheskaya', hasTransfer: false, order: 3 },
  { id: 'sok-4', name: 'Сокольники', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['bolshaya-koltsevaya'], order: 4 },
  { id: 'sok-5', name: 'Красносельская', lineId: 'sokolnicheskaya', hasTransfer: false, order: 5 },
  { id: 'sok-6', name: 'Комсомольская', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 6 },
  { id: 'sok-7', name: 'Красные ворота', lineId: 'sokolnicheskaya', hasTransfer: false, order: 7 },
  { id: 'sok-8', name: 'Чистые пруды', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['lyublinsko-dmitrovskaya', 'kaluzhsko-rizhskaya'], order: 8 },
  { id: 'sok-9', name: 'Лубянка', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 9 },
  { id: 'sok-10', name: 'Охотный ряд', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya', 'arbatsko-pokrovskaya'], order: 10 },
  { id: 'sok-11', name: 'Библиотека имени Ленина', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'filevskaya', 'serpukhovsko-timiryazevskaya'], order: 11 },
  { id: 'sok-12', name: 'Кропоткинская', lineId: 'sokolnicheskaya', hasTransfer: false, order: 12 },
  { id: 'sok-13', name: 'Парк культуры', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 13 },
  { id: 'sok-14', name: 'Фрунзенская', lineId: 'sokolnicheskaya', hasTransfer: false, order: 14 },
  { id: 'sok-15', name: 'Спортивная', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['mck'], order: 15 },
  { id: 'sok-16', name: 'Воробьёвы горы', lineId: 'sokolnicheskaya', hasTransfer: false, order: 16 },
  { id: 'sok-17', name: 'Университет', lineId: 'sokolnicheskaya', hasTransfer: false, order: 17 },
  { id: 'sok-18', name: 'Проспект Вернадского', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['bolshaya-koltsevaya'], order: 18 },
  { id: 'sok-19', name: 'Юго-Западная', lineId: 'sokolnicheskaya', hasTransfer: false, order: 19 },
  { id: 'sok-20', name: 'Тропарёво', lineId: 'sokolnicheskaya', hasTransfer: false, order: 20 },
  { id: 'sok-21', name: 'Румянцево', lineId: 'sokolnicheskaya', hasTransfer: false, order: 21 },
  { id: 'sok-22', name: 'Саларьево', lineId: 'sokolnicheskaya', hasTransfer: false, order: 22 },
  { id: 'sok-23', name: 'Филатов Луг', lineId: 'sokolnicheskaya', hasTransfer: false, order: 23 },
  { id: 'sok-24', name: 'Прокшино', lineId: 'sokolnicheskaya', hasTransfer: false, order: 24 },
  { id: 'sok-25', name: 'Ольховая', lineId: 'sokolnicheskaya', hasTransfer: false, order: 25 },
  { id: 'sok-26', name: 'Новомосковская', lineId: 'sokolnicheskaya', hasTransfer: true, transferTo: ['troitskaya'], order: 26 },
  { id: 'sok-0', name: 'Потапово', lineId: 'sokolnicheskaya', hasTransfer: false, order: 27 },

  { id: 'zam-1', name: 'Ховрино', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 1 },
  { id: 'zam-2', name: 'Беломорская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 2 },
  { id: 'zam-3', name: 'Речной вокзал', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 3 },
  { id: 'zam-4', name: 'Водный стадион', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 4 },
  { id: 'zam-5', name: 'Войковская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 5 },
  { id: 'zam-6', name: 'Сокол', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 6 },
  { id: 'zam-7', name: 'Аэропорт', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 7 },
  { id: 'zam-8', name: 'Динамо', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 8 },
  { id: 'zam-9', name: 'Белорусская', lineId: 'zamoskvoretskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 9 },
  { id: 'zam-10', name: 'Маяковская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 10 },
  { id: 'zam-11', name: 'Тверская', lineId: 'zamoskvoretskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 11 },
  { id: 'zam-12', name: 'Театральная', lineId: 'zamoskvoretskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 12 },
  { id: 'zam-13', name: 'Новокузнецкая', lineId: 'zamoskvoretskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 13 },
  { id: 'zam-14', name: 'Павелецкая', lineId: 'zamoskvoretskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 14 },
  { id: 'zam-15', name: 'Автозаводская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 15 },
  { id: 'zam-16', name: 'Технопарк', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 16 },
  { id: 'zam-17', name: 'Коломенская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 17 },
  { id: 'zam-18', name: 'Каширская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 18 },
  { id: 'zam-19', name: 'Кантемировская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 19 },
  { id: 'zam-20', name: 'Царицыно', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 20 },
  { id: 'zam-21', name: 'Орехово', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 21 },
  { id: 'zam-22', name: 'Домодедовская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 22 },
  { id: 'zam-23', name: 'Красногвардейская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 23 },
  { id: 'zam-24', name: 'Алма-Атинская', lineId: 'zamoskvoretskaya', hasTransfer: false, order: 24 },

  { id: 'arb-1', name: 'Пятницкое шоссе', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 1 },
  { id: 'arb-2', name: 'Митино', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 2 },
  { id: 'arb-3', name: 'Волоколамская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 3 },
  { id: 'arb-4', name: 'Мякинино', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 4 },
  { id: 'arb-5', name: 'Строгино', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 5 },
  { id: 'arb-6', name: 'Крылатское', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 6 },
  { id: 'arb-7', name: 'Молодёжная', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 7 },
  { id: 'arb-8', name: 'Кунцевская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['filevskaya'], order: 8 },
  { id: 'arb-9', name: 'Славянский бульвар', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 9 },
  { id: 'arb-10', name: 'Парк Победы', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['kalininskaya', 'solntsevskaya'], order: 10 },
  { id: 'arb-11', name: 'Киевская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['koltsevaya', 'filevskaya'], order: 11 },
  { id: 'arb-12', name: 'Смоленская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['filevskaya'], order: 12 },
  { id: 'arb-13', name: 'Арбатская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 13 },
  { id: 'arb-14', name: 'Площадь Революции', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 14 },
  { id: 'arb-15', name: 'Курская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 15 },
  { id: 'arb-16', name: 'Бауманская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 16 },
  { id: 'arb-17', name: 'Электрозаводская', lineId: 'arbatsko-pokrovskaya', hasTransfer: true, transferTo: ['bolshaya-koltsevaya'], order: 17 },
  { id: 'arb-18', name: 'Семёновская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 18 },
  { id: 'arb-19', name: 'Партизанская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 19 },
  { id: 'arb-20', name: 'Измайловская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 20 },
  { id: 'arb-21', name: 'Первомайская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 21 },
  { id: 'arb-22', name: 'Щёлковская', lineId: 'arbatsko-pokrovskaya', hasTransfer: false, order: 22 },

  { id: 'fil-1', name: 'Кунцевская', lineId: 'filevskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya'], order: 1 },
  { id: 'fil-2', name: 'Пионерская', lineId: 'filevskaya', hasTransfer: false, order: 2 },
  { id: 'fil-3', name: 'Филёвский парк', lineId: 'filevskaya', hasTransfer: false, order: 3 },
  { id: 'fil-4', name: 'Багратионовская', lineId: 'filevskaya', hasTransfer: false, order: 4 },
  { id: 'fil-5', name: 'Фили', lineId: 'filevskaya', hasTransfer: false, order: 5 },
  { id: 'fil-6', name: 'Кутузовская', lineId: 'filevskaya', hasTransfer: false, order: 6 },
  { id: 'fil-7', name: 'Студенческая', lineId: 'filevskaya', hasTransfer: false, order: 7 },
  { id: 'fil-8', name: 'Киевская', lineId: 'filevskaya', hasTransfer: true, transferTo: ['koltsevaya', 'arbatsko-pokrovskaya'], order: 8 },
  { id: 'fil-9', name: 'Смоленская', lineId: 'filevskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya'], order: 9 },
  { id: 'fil-10', name: 'Арбатская', lineId: 'filevskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 10 },
  { id: 'fil-11', name: 'Александровский сад', lineId: 'filevskaya', hasTransfer: false, order: 11 },
  { id: 'fil-12', name: 'Выставочная', lineId: 'filevskaya', hasTransfer: false, order: 12 },
  { id: 'fil-13', name: 'Международная', lineId: 'filevskaya', hasTransfer: false, order: 13 },

  { id: 'kol-1', name: 'Киевская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'filevskaya'], order: 1 },
  { id: 'kol-2', name: 'Парк культуры', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 2 },
  { id: 'kol-3', name: 'Октябрьская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['kaluzhsko-rizhskaya'], order: 3 },
  { id: 'kol-4', name: 'Добрынинская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['serpukhovsko-timiryazevskaya'], order: 4 },
  { id: 'kol-5', name: 'Павелецкая', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 5 },
  { id: 'kol-6', name: 'Таганская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 6 },
  { id: 'kol-7', name: 'Курская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya'], order: 7 },
  { id: 'kol-8', name: 'Комсомольская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 8 },
  { id: 'kol-9', name: 'Проспект Мира', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['kaluzhsko-rizhskaya'], order: 9 },
  { id: 'kol-10', name: 'Новослободская', lineId: 'koltsevaya', hasTransfer: false, order: 10 },
  { id: 'kol-11', name: 'Белорусская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 11 },
  { id: 'kol-12', name: 'Краснопресненская', lineId: 'koltsevaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 12 },

  { id: 'kal-1', name: 'Медведково', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 1 },
  { id: 'kal-2', name: 'Бабушкинская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 2 },
  { id: 'kal-3', name: 'Свиблово', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 3 },
  { id: 'kal-4', name: 'Ботанический сад', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 4 },
  { id: 'kal-5', name: 'ВДНХ', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 5 },
  { id: 'kal-6', name: 'Алексеевская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 6 },
  { id: 'kal-7', name: 'Рижская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 7 },
  { id: 'kal-8', name: 'Проспект Мира', lineId: 'kaluzhsko-rizhskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 8 },
  { id: 'kal-9', name: 'Сухаревская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 9 },
  { id: 'kal-10', name: 'Тургеневская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 10 },
  { id: 'kal-11', name: 'Китай-город', lineId: 'kaluzhsko-rizhskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 11 },
  { id: 'kal-12', name: 'Третьяковская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 12 },
  { id: 'kal-13', name: 'Октябрьская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 13 },
  { id: 'kal-14', name: 'Шаболовская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 14 },
  { id: 'kal-15', name: 'Ленинский проспект', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 15 },
  { id: 'kal-16', name: 'Академическая', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 16 },
  { id: 'kal-17', name: 'Профсоюзная', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 17 },
  { id: 'kal-18', name: 'Новые Черёмушки', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 18 },
  { id: 'kal-19', name: 'Калужская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 19 },
  { id: 'kal-20', name: 'Беляево', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 20 },
  { id: 'kal-21', name: 'Коньково', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 21 },
  { id: 'kal-22', name: 'Тёплый Стан', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 22 },
  { id: 'kal-23', name: 'Ясенево', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 23 },
  { id: 'kal-24', name: 'Новоясеневская', lineId: 'kaluzhsko-rizhskaya', hasTransfer: false, order: 24 },

  { id: 'tag-1', name: 'Планерная', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 1 },
  { id: 'tag-2', name: 'Сходненская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 2 },
  { id: 'tag-3', name: 'Тушинская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 3 },
  { id: 'tag-4', name: 'Спартак', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 4 },
  { id: 'tag-5', name: 'Щукинская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 5 },
  { id: 'tag-6', name: 'Октябрьское Поле', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 6 },
  { id: 'tag-7', name: 'Полежаевская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 7 },
  { id: 'tag-8', name: 'Беговая', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 8 },
  { id: 'tag-9', name: 'Улица 1905 года', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 9 },
  { id: 'tag-10', name: 'Баррикадная', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 10 },
  { id: 'tag-11', name: 'Пушкинская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 11 },
  { id: 'tag-12', name: 'Кузнецкий Мост', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 12 },
  { id: 'tag-13', name: 'Китай-город', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: true, transferTo: ['kaluzhsko-rizhskaya'], order: 13 },
  { id: 'tag-14', name: 'Таганская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 14 },
  { id: 'tag-15', name: 'Пролетарская', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 15 },
  { id: 'tag-16', name: 'Волгоградский проспект', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 16 },
  { id: 'tag-17', name: 'Текстильщики', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 17 },
  { id: 'tag-18', name: 'Кузьминки', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 18 },
  { id: 'tag-19', name: 'Рязанский проспект', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 19 },
  { id: 'tag-20', name: 'Выхино', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 20 },
  { id: 'tag-21', name: 'Лермонтовский проспект', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 21 },
  { id: 'tag-22', name: 'Жулебино', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 22 },
  { id: 'tag-23', name: 'Котельники', lineId: 'tagansko-krasnopresnenskaya', hasTransfer: false, order: 23 },

  { id: 'kalin-1', name: 'Новокосино', lineId: 'kalininskaya', hasTransfer: false, order: 1 },
  { id: 'kalin-2', name: 'Новогиреево', lineId: 'kalininskaya', hasTransfer: false, order: 2 },
  { id: 'kalin-3', name: 'Перово', lineId: 'kalininskaya', hasTransfer: false, order: 3 },
  { id: 'kalin-4', name: 'Шоссе Энтузиастов', lineId: 'kalininskaya', hasTransfer: false, order: 4 },
  { id: 'kalin-5', name: 'Авиамоторная', lineId: 'kalininskaya', hasTransfer: false, order: 5 },
  { id: 'kalin-6', name: 'Площадь Ильича', lineId: 'kalininskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 6 },
  { id: 'kalin-7', name: 'Марксистская', lineId: 'kalininskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 7 },
  { id: 'kalin-8', name: 'Третьяковская', lineId: 'kalininskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 8 },
  { id: 'kalin-9', name: 'Деловой центр', lineId: 'kalininskaya', hasTransfer: true, transferTo: ['bolshaya-koltsevaya'], order: 9 },
  { id: 'kalin-10', name: 'Парк Победы', lineId: 'kalininskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'solntsevskaya'], order: 10 },
  { id: 'kalin-11', name: 'Минская', lineId: 'kalininskaya', hasTransfer: false, order: 11 },
  { id: 'kalin-12', name: 'Ломоносовский проспект', lineId: 'kalininskaya', hasTransfer: false, order: 12 },
  { id: 'kalin-13', name: 'Раменки', lineId: 'kalininskaya', hasTransfer: false, order: 13 },
  { id: 'kalin-14', name: 'Мичуринский проспект', lineId: 'kalininskaya', hasTransfer: false, order: 14 },
  { id: 'kalin-15', name: 'Озёрная', lineId: 'kalininskaya', hasTransfer: false, order: 15 },
  { id: 'kalin-16', name: 'Говорово', lineId: 'kalininskaya', hasTransfer: false, order: 16 },
  { id: 'kalin-17', name: 'Солнцево', lineId: 'kalininskaya', hasTransfer: false, order: 17 },
  { id: 'kalin-18', name: 'Боровское шоссе', lineId: 'kalininskaya', hasTransfer: false, order: 18 },
  { id: 'kalin-19', name: 'Новопеределкино', lineId: 'kalininskaya', hasTransfer: false, order: 19 },
  { id: 'kalin-20', name: 'Рассказовка', lineId: 'kalininskaya', hasTransfer: false, order: 20 },

  { id: 'ser-1', name: 'Алтуфьево', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 1 },
  { id: 'ser-2', name: 'Бибирево', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 2 },
  { id: 'ser-3', name: 'Отрадное', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 3 },
  { id: 'ser-4', name: 'Владыкино', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 4 },
  { id: 'ser-5', name: 'Петровско-Разумовская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 5 },
  { id: 'ser-6', name: 'Тимирязевская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 6 },
  { id: 'ser-7', name: 'Дмитровская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 7 },
  { id: 'ser-8', name: 'Савёловская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 8 },
  { id: 'ser-9', name: 'Менделеевская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 9 },
  { id: 'ser-10', name: 'Цветной бульвар', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 10 },
  { id: 'ser-11', name: 'Чеховская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 11 },
  { id: 'ser-12', name: 'Боровицкая', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya'], order: 12 },
  { id: 'ser-13', name: 'Полянка', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 13 },
  { id: 'ser-14', name: 'Серпуховская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: true, transferTo: ['koltsevaya'], order: 14 },
  { id: 'ser-15', name: 'Тульская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 15 },
  { id: 'ser-16', name: 'Нагатинская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 16 },
  { id: 'ser-17', name: 'Нагорная', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 17 },
  { id: 'ser-18', name: 'Нахимовский проспект', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 18 },
  { id: 'ser-19', name: 'Севастопольская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 19 },
  { id: 'ser-20', name: 'Чертановская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 20 },
  { id: 'ser-21', name: 'Южная', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 21 },
  { id: 'ser-22', name: 'Пражская', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 22 },
  { id: 'ser-23', name: 'Улица Академика Янгеля', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 23 },
  { id: 'ser-24', name: 'Аннино', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 24 },
  { id: 'ser-25', name: 'Бульвар Дмитрия Донского', lineId: 'serpukhovsko-timiryazevskaya', hasTransfer: false, order: 25 },

  { id: 'lyub-1', name: 'Селигерская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 1 },
  { id: 'lyub-2', name: 'Верхние Лихоборы', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 2 },
  { id: 'lyub-3', name: 'Окружная', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 3 },
  { id: 'lyub-4', name: 'Петровско-Разумовская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 4 },
  { id: 'lyub-5', name: 'Фонвизинская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 5 },
  { id: 'lyub-6', name: 'Бутырская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 6 },
  { id: 'lyub-7', name: 'Марьина Роща', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 7 },
  { id: 'lyub-8', name: 'Достоевская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 8 },
  { id: 'lyub-9', name: 'Трубная', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 9 },
  { id: 'lyub-10', name: 'Сретенский бульвар', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 10 },
  { id: 'lyub-11', name: 'Чкаловская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 11 },
  { id: 'lyub-12', name: 'Римская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 12 },
  { id: 'lyub-13', name: 'Крестьянская Застава', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 13 },
  { id: 'lyub-14', name: 'Дубровка', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 14 },
  { id: 'lyub-15', name: 'Кожуховская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 15 },
  { id: 'lyub-16', name: 'Печатники', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 16 },
  { id: 'lyub-17', name: 'Волжская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 17 },
  { id: 'lyub-18', name: 'Люблино', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 18 },
  { id: 'lyub-19', name: 'Братиславская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 19 },
  { id: 'lyub-20', name: 'Марьино', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 20 },
  { id: 'lyub-21', name: 'Борисово', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 21 },
  { id: 'lyub-22', name: 'Шипиловская', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 22 },
  { id: 'lyub-23', name: 'Зябликово', lineId: 'lyublinsko-dmitrovskaya', hasTransfer: false, order: 23 },

  { id: 'but-1', name: 'Улица Старокачаловская', lineId: 'butovskaya', hasTransfer: false, order: 1 },
  { id: 'but-2', name: 'Улица Скобелевская', lineId: 'butovskaya', hasTransfer: false, order: 2 },
  { id: 'but-3', name: 'Бульвар Адмирала Ушакова', lineId: 'butovskaya', hasTransfer: false, order: 3 },
  { id: 'but-4', name: 'Улица Горчакова', lineId: 'butovskaya', hasTransfer: false, order: 4 },
  { id: 'but-5', name: 'Бунинская аллея', lineId: 'butovskaya', hasTransfer: false, order: 5 },

  { id: 'mon-1', name: 'Тимирязевская', lineId: 'monorail', hasTransfer: true, transferTo: ['serpukhovsko-timiryazevskaya'], order: 1 },
  { id: 'mon-2', name: 'Улица Милашенкова', lineId: 'monorail', hasTransfer: false, order: 2 },
  { id: 'mon-3', name: 'Телецентр', lineId: 'monorail', hasTransfer: false, order: 3 },
  { id: 'mon-4', name: 'Улица Академика Королёва', lineId: 'monorail', hasTransfer: false, order: 4 },
  { id: 'mon-5', name: 'ВДНХ', lineId: 'monorail', hasTransfer: true, transferTo: ['kaluzhsko-rizhskaya'], order: 5 },
  { id: 'mon-6', name: 'Улица Сергея Эйзенштейна', lineId: 'monorail', hasTransfer: false, order: 6 },

  { id: 'bol-1', name: 'Савёловская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['serpukhovsko-timiryazevskaya'], order: 1 },
  { id: 'bol-2', name: 'Петровский парк', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 2 },
  { id: 'bol-3', name: 'ЦСКА', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 3 },
  { id: 'bol-4', name: 'Хорошёвская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 4 },
  { id: 'bol-5', name: 'Шелепиха', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 5 },
  { id: 'bol-6', name: 'Деловой центр', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kalininskaya'], order: 6 },
  { id: 'bol-7', name: 'Кунцевская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'filevskaya'], order: 7 },
  { id: 'bol-8', name: 'Мнёвники', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 8 },
  { id: 'bol-9', name: 'Народное Ополчение', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 9 },
  { id: 'bol-10', name: 'Терехово', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 10 },
  { id: 'bol-11', name: 'Карамышевская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 11 },
  { id: 'bol-12', name: 'Улица Новаторов', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 12 },
  { id: 'bol-13', name: 'Проспект Вернадского', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 13 },
  { id: 'bol-14', name: 'Мичуринский проспект', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kalininskaya'], order: 14 },
  { id: 'bol-15', name: 'Аминьевская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 15 },
  { id: 'bol-16', name: 'Давыдково', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 16 },
  { id: 'bol-17', name: 'Ломоносовский проспект', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kalininskaya'], order: 17 },
  { id: 'bol-18', name: 'Минская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kalininskaya'], order: 18 },
  { id: 'bol-19', name: 'Парк Победы', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'kalininskaya', 'solntsevskaya'], order: 19 },
  { id: 'bol-20', name: 'Проспект Вернадского', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 20 },
  { id: 'bol-21', name: 'Воронцовская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 21 },
  { id: 'bol-22', name: 'Зюзино', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 22 },
  { id: 'bol-23', name: 'Каховская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 23 },
  { id: 'bol-24', name: 'Варшавская', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 24 },
  { id: 'bol-25', name: 'Каширская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 25 },
  { id: 'bol-26', name: 'Технопарк', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['zamoskvoretskaya'], order: 26 },
  { id: 'bol-27', name: 'Кленовый бульвар', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 27 },
  { id: 'bol-28', name: 'Нагатинский Затон', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 28 },
  { id: 'bol-29', name: 'Печатники', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['lyublinsko-dmitrovskaya'], order: 29 },
  { id: 'bol-30', name: 'Текстильщики', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['tagansko-krasnopresnenskaya'], order: 30 },
  { id: 'bol-31', name: 'Нижегородская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['nekrasovskaya'], order: 31 },
  { id: 'bol-32', name: 'Лефортово', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 32 },
  { id: 'bol-33', name: 'Авиамоторная', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kalininskaya'], order: 33 },
  { id: 'bol-34', name: 'Лефортово', lineId: 'bolshaya-koltsevaya', hasTransfer: false, order: 34 },
  { id: 'bol-35', name: 'Электрозаводская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya'], order: 35 },
  { id: 'bol-36', name: 'Сокольники', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['sokolnicheskaya'], order: 36 },
  { id: 'bol-37', name: 'Рижская', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['kaluzhsko-rizhskaya'], order: 37 },
  { id: 'bol-38', name: 'Марьина Роща', lineId: 'bolshaya-koltsevaya', hasTransfer: true, transferTo: ['lyublinsko-dmitrovskaya'], order: 38 },

  { id: 'nek-1', name: 'Косино', lineId: 'nekrasovskaya', hasTransfer: false, order: 1 },
  { id: 'nek-2', name: 'Улица Дмитриевского', lineId: 'nekrasovskaya', hasTransfer: false, order: 2 },
  { id: 'nek-3', name: 'Лухмановская', lineId: 'nekrasovskaya', hasTransfer: false, order: 3 },
  { id: 'nek-4', name: 'Некрасовка', lineId: 'nekrasovskaya', hasTransfer: false, order: 4 },
  { id: 'nek-5', name: 'Юго-Восточная', lineId: 'nekrasovskaya', hasTransfer: false, order: 5 },
  { id: 'nek-6', name: 'Окская', lineId: 'nekrasovskaya', hasTransfer: false, order: 6 },
  { id: 'nek-7', name: 'Стахановская', lineId: 'nekrasovskaya', hasTransfer: false, order: 7 },
  { id: 'nek-8', name: 'Нижегородская', lineId: 'nekrasovskaya', hasTransfer: true, transferTo: ['bolshaya-koltsevaya'], order: 8 },

  { id: 'sol-1', name: 'Рассказовка', lineId: 'solntsevskaya', hasTransfer: false, order: 1 },
  { id: 'sol-2', name: 'Новопеределкино', lineId: 'solntsevskaya', hasTransfer: false, order: 2 },
  { id: 'sol-3', name: 'Боровское шоссе', lineId: 'solntsevskaya', hasTransfer: false, order: 3 },
  { id: 'sol-4', name: 'Солнцево', lineId: 'solntsevskaya', hasTransfer: false, order: 4 },
  { id: 'sol-5', name: 'Говорово', lineId: 'solntsevskaya', hasTransfer: false, order: 5 },
  { id: 'sol-6', name: 'Озёрная', lineId: 'solntsevskaya', hasTransfer: false, order: 6 },
  { id: 'sol-7', name: 'Мичуринский проспект', lineId: 'solntsevskaya', hasTransfer: false, order: 7 },
  { id: 'sol-8', name: 'Раменки', lineId: 'solntsevskaya', hasTransfer: false, order: 8 },
  { id: 'sol-9', name: 'Ломоносовский проспект', lineId: 'solntsevskaya', hasTransfer: false, order: 9 },
  { id: 'sol-10', name: 'Минская', lineId: 'solntsevskaya', hasTransfer: false, order: 10 },
  { id: 'sol-11', name: 'Парк Победы', lineId: 'solntsevskaya', hasTransfer: true, transferTo: ['arbatsko-pokrovskaya', 'kalininskaya'], order: 11 },
];